### ISSUE TITLE
nutanix_vm: adding CDrom requires passing size_mib

### ISSUE THREAD

**Issue by yannickstruyf3** [ideadevice/ansible-ahv-provider-plugin#22]
When creating a VM with a cdrom size_mib must be passed:
```
      disk_list:
          - clone_from_image: "{{image_name}}"
            device_type: "DISK"
            adapter_type: "SCSI"
            size_mib: 100000
          - size_mib: 100000
            device_type: "DISK"
            adapter_type: "SCSI"
          - device_type: "CDROM"
            adapter_type: "IDE"
            size_mib: 1
```
