### ISSUE TITLE
Usage of nutanix_vm_info and nutanix_image_info should be consistent

### ISSUE THREAD

**Issue by yannickstruyf3** [ideadevice/ansible-ahv-provider-plugin#24]
Retrieving info for a vm requires following structure:
```
    - name: "Getting info for image {{ vm_image_name }}"
      nutanix_image_info:
        image_name: "{{vm_image_name}}"
        validate_certs: no
```
For a VM this is required:
```
   nutanix_vm_info:
     validate_certs: no
     data:
       filter: "vm_name=={{ item }}"
       offset: 0
       length: 100
       sort_attribute: ASCENDING
       sort_order: ASCENDING
```
There is not option to specific a vm_name while it is possible to pass image_name in the `nutanix_image_info` task
